### ISSUE TITLE
[FEATURE] Add local option to "Destinations"

### ISSUE THREAD

**Issue by jakesmorrison** [eduardolat/pgbackweb#1]
Project looks great so far. I was wondering if it would be possible to also add "Local Destinations"?

I think as far as options you would have:

- Name -> "Local Backup"
- Path -> "/my_file_path" This path is added to the volume.

**Comment by eduardolat** [comment]
@jakesmorrison For the moment only s3 is supported, do you think that local destinations is a great addition?

I think they can be stored inside a fixed path, f.e. /backups/{backup_id}/yyyy/mm/dd/dump-{data}.zip and then it can be mounted inside a volume

In my mind this can be useful to give completly freedom to sync to other places for example with rclone or other similar tools

**Comment by eduardolat** [comment]
> Hello @jakesmorrison, you can use MinIO to save backups to your local storage.

Yes, that's a perfect solution! But I don't recommend putting all your eggs in one basket.

I can recommend that you use third-party hosted services such as Backblaze B2, Cloudflare R2 or S3.

These providers give you guarantees, privacy and security of your data, and these aforementioned options have quite generous free tiers, I like Backblaze the most.

**Comment by jakesmorrison** [comment]
@ GhaithKhmili thanks for the suggestion. I will look into it!

Thanks for the suggestions and tool @eduardolat. I use Proton as my cloud storage. It is a bit convoluted but I use Synthing to backup files from my NAS (where pgbackweb is running) to my PC (where Proton Drive is). Point is the eggs are in more than 1 basket.

**Comment by eduardolat** [comment]
@jakesmorrison Great to hear that you have backups in a location outside your network (Proton), for now you can go with the Minio option, but in the not too distant future there may be the option of local backups, so don't worry, it will soon be much easier for you, I hope you enjoy PG Back Web.

**Comment by alex-grandson** [comment]
thanks to @eduardolat  for the encouraging saying. I'm also interested in this project. you're doing good 🙏🏻

**Comment by rursache** [comment]
also interested in this, its pretty much useless without local storage backups

**Comment by eduardolat** [comment]
> also interested in this, its pretty much useless without local storage backups

I'm putting in the work and time to do this, I would appreciate a little cordiality.

**Comment by eduardolat** [comment]
For all those interested in this feature, it will be included in a release tomorrow
https://github.com/eduardolat/pgbackweb/pull/17

**Comment by eduardolat** [comment]
New version released
