### ISSUE TITLE
[FEATURE] Alert system

### ISSUE THREAD

**Issue by eduardolat** [eduardolat/pgbackweb#10]

**Comment by WladyX** [comment]
Maybe also add prometheus metrics? :)

**Comment by PaxITIS** [comment]
Perhaps it would be good to have the ability to send notification e-mails if the backup fails or completes.

**Comment by eduardolat** [comment]
> Perhaps it would be good to have the ability to send notification e-mails if the backup fails or completes.

This is going to have webhooks, so you can configure any system like zapier or ntify to be alerted as you prefer.

**Comment by eduardolat** [comment]
> Maybe also add prometheus metrics? :)

Can you explain a little more about your requirement and how it relates to the alert system?

**Comment by WladyX** [comment]
By exposing prometheus metrics one could add alerts for when the backups are failing or taking too long and also could create a grafana dashboard, you can check out the velero/kasten metrics/dashboards implementations.
I have installed pgbackweb on a k8s cluster btw :)
Thanks for sharing it!

**Comment by eduardolat** [comment]
This has been published in the v0.3.0 release https://github.com/eduardolat/pgbackweb/releases/tag/0.3.0

**Comment by WladyX** [comment]
That's great, thank you!
Are there variables that we can pass to the body? Like DB_NAME? I'm searching for docs/code to see what is available.
Thanks again!

**Comment by eduardolat** [comment]
> That's great, thank you! Are there variables that we can pass to the body? Like DB_NAME? I'm searching for docs/code to see what is available. Thanks again!

No for the moment, but you can open a new issue because this is something that has to be done at some point.

**Comment by WladyX** [comment]
Cool, thanks, created https://github.com/eduardolat/pgbackweb/issues/46
