### ISSUE TITLE
FR - Backup to network shared folders

### ISSUE THREAD

**Issue by poudenes** [eduardolat/pgbackweb#14]
Hi,

Nice tool. Would be great to be able to backup to network shared folders.
I wanna backup my Databases from system 1 to my Synology NAS.

Greets
Peter

**Comment by eduardolat** [comment]
@poudenes There is a feature pending implementation that allows local backups, so you can mount the docker volume wherever you want, does this work for your requirement?
https://github.com/eduardolat/pgbackweb/issues/1

**Comment by eduardolat** [comment]
Duplicated of #1
