### ISSUE TITLE
[FEATURE REQUEST] save backups on local storage on given path

### ISSUE THREAD

**Issue by sinawic** [eduardolat/pgbackweb#19]
hi
i wasn't able to use it bec of the destination settings
why should there only be `s3 object storage` as the destination.
i have mounted a volume to `/backups` inside the container
and i want to be able to store the backups in there instead of sending to a s3 storage

thanks in advance!

**Comment by eduardolat** [comment]
Duplicate of #1 

A new version will be released today that includes exactly this feature in the same way you describe so there you have it :)

**Comment by sinawic** [comment]
hey
I can confirm that the feature is added
and is working as expected!

thanks for all the effort <3

here's [my channel](https://www.youtube.com/channel/UC33nD8gkUUAJr36E9di1bDA) link tho
I would appreciate if u give a visit
and I'll let u know when I get the video done!

@eduardolat

**Comment by eduardolat** [comment]
Great, I'll be keeping an eye out

**Comment by sinawic** [comment]
hey @eduardolat 
here's the video url 
i hope you like it
https://www.youtube.com/watch?v=vf7SLrSO8sw

**Comment by sinawic** [comment]
also if you liked it
I'd really appreciate if you put the link to the video somewhere in the readme or something
anyway thanks for the tool :+1:

**Comment by eduardolat** [comment]
Hi @sinawic, I've seen your video and it's great! Thank you very much for making it.

I've put it in the readme as a guide, I really appreciate it.

Don't forget that we have a discord server where we can chat more comfortably.

**Comment by sinawic** [comment]
thanks really
i really appreciate it
of course i'll try to join it
