### ISSUE TITLE
Cannot create first user 

### ISSUE THREAD

**Issue by Bartrpc** [eduardolat/pgbackweb#22]
![image](https://github.com/user-attachments/assets/40376712-5c91-4b52-8ef1-b660797173ec)
Hi
After setting up everything I can't create my user account, there is no any pop up when clicking on 'Create user and continue'

**Comment by eduardolat** [comment]
Can you inspect your network requests and browser console and see if something is wrong? it should work, you can also try on a fresh browser

**Comment by Bartrpc** [comment]
It turns out that Bitdefender on my work laptop had detected suspicious network activity and blocked any suspicious activities. I've also deployed pgbackweb on my home network and I didn't notice any problems. Sorry for bothering you, thanks for the reply, and huge kudos to you <3 ! Great work, mate !

**Comment by Bartrpc** [comment]
I've already did that :) also I'm planning to create some content on social media on pgbackweb 👍🏼

**Comment by eduardolat** [comment]
Great, let's get to it! Don't forget to send me the links so I can take a look. 🫶
