### ISSUE TITLE
add support for mysql and postgresql 9 - 10

### ISSUE THREAD

**Issue by insinfo** [eduardolat/pgbackweb#43]
add support for mysql and postgresql 9 - 10

**Comment by eduardolat** [comment]
Any version of PostgreSQL older than 12 is already "obsolete", you can see them at this link: https://www.postgresql.org/support/versioning/

Even version 12 has its EOL on November 14, 2024, and that is the main reason why it is not supported.

You should really consider upgrading your Postgres version, both for security and compatibility.

**Comment by insinfo** [comment]
Where I work we have many legacy systems that we cannot update, the people who developed them are no longer with us and we have few resources and people, so it is not possible to simply update these applications, we have PostgreSQL 9.3, 10,11,12 and 16 databases and MySQL

**Comment by camaeel** [comment]
@insinfo But don't expect maintainers of other software to keep those old versions. It may be very hard to have old library versions mixed with new ones in one software.
And this is also responsibility of management to keep enough people to maintain all the legacy apps that are in the company and also keep them up to date with current library versions and security vulnerabilities patched.

**Comment by eduardolat** [comment]
@camaeel you are completly right. For the moment PG Back Web will only include the postgresql versions that are officially supported by them and in the future, older versions will be removed from the latest releases 

https://www.postgresql.org/support/versioning/

**Comment by eduardolat** [comment]
@insinfo In the company you work, they should update the components, or at least sponsor or help the project so we can add that kind of support

**Comment by insinfo** [comment]
I work in a small city hall in a small town in the interior of Rio de Janeiro / Brazil, we simply do not have the financial resources and we also cannot find qualified workers with the salary we can offer. I believe that there are many who find themselves in this situation.

I understand that it is difficult to maintain support for older versions, but the PostgreSQL protocol has not changed much since version 9, and for simple databases that do not use specialized features of newer PostgreSQL versions there is no difference, and PostgreSQL 16 tools such as pg_dump and psql work with older databases without problems, and almost all PostgreSQL drivers work with older versions.

**Comment by insinfo** [comment]
And this support for version 9-10 does not need to be forever, it could be limited to the current version and then deprecate them.

**Comment by insinfo** [comment]
We can invariably update legacy applications but this will be slow and time consuming, we currently only have 2 developers to support multiple applications.
