### ISSUE TITLE
Using ssh tunnel to access DB

### ISSUE THREAD

**Issue by alex-grandson** [eduardolat/pgbackweb#5]
This might be the case when DB hosted locally without exposed ports like in docker compose with postgres service ports like `127.0.0.1:5432:5432`. I understand that this is not a high priority right now, but it would be very cool to have such functionality. Also it would be nice to have an opportunity to load private ssh key or use log/pass methods on choice.
Thanks

**Comment by eduardolat** [comment]
If your postgres is on the same server you can use docker networking to connect without having to expose the port outside the server

**Comment by iamxiyang** [comment]
My Postgres and pgbackweb are not on the same server. Does it support connecting to Postgres via SSH?
