### ISSUE TITLE
Backups Not Encrypted

### ISSUE THREAD

**Issue by nealhead** [eduardolat/pgbackweb#6]
It would appear that the backups in the S3 bucket are stored in an unencrypted ZIP file. Is this intended?

**Comment by eduardolat** [comment]
Yes, that's how it works.

PG Back Web encrypts the data stored in the database.

Regarding storage, data is encrypted by default on the majority of S3 storage providers, so the responsibility is delegated to them.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingEncryption.html
https://www.backblaze.com/docs/cloud-storage-server-side-encryption
https://docs.wasabi.com/docs/how-secure-is-my-data-1
https://developers.cloudflare.com/r2/reference/data-security/
https://www.digitalocean.com/security/shared-responsibility-model-spaces

**Comment by eduardolat** [comment]
Maybe in the future when other features on the to-do list are done we can add a flag to add an encryption layer by PG Back Web
