### ISSUE TITLE
[request] Other Relational Databases 

### ISSUE THREAD

**Issue by Aesop7** [eduardolat/pgbackweb#60]
First and foremost, thank you for developing such a great tool for PostgreSQL backups. Having experienced many headaches with Barman, the user-friendly web interface is a breath of fresh air.

Like many others I'm sure, the infrastructure i'm working in includes other databases, primarily MySQL/MariaDB.  I'd see a ton of value in a unified backup solution, extending PGBackWeb's capabilities to support these databases for:

-  Centralized Backup Management: A single platform to look at for for multiple databases simplifies workflows
-  Consistent Backup Practices: Uniformity in backup procedures across different databases promotes reliability and ease of maintenance.
-  Broadened PGBackWeb's Adoption: Supporting a wider range of databases would attract a larger user base, fostering a more diverse and engaged community.

Thank you for considering this feature request. I'm looking forward to the continued evolution of PGBackWeb and are excited about the possibilities this enhancement could bring.

**Comment by eduardolat** [comment]
Hi @Aesop7 , Let's continue the conversation in #24 where more people are involved
