### ISSUE TITLE
希望支持PG17以及物理备份，谢谢

### ISSUE THREAD

**Issue by dbbao** [eduardolat/pgbackweb#61]

**Comment by Shayennn** [comment]
เห้ ใช้ภาษาอังกฤษคุยเถอะ ที่นี่ไม่ค่อยมีคนอ่านภาษาบ้านคุณออกหรอกนะ แล้วเรื่องที่คุณถามก็เคยมีคนถามแล้ว ครั้งหน้าก็ลองย้อนไปพยายามอ่านดูก่อนนะ

https://github.com/eduardolat/pgbackweb/issues/53
